version: '3.8'

services:
  # Main ERP Application
  app:
    build: ../../
    container_name: buildflow-erp
    restart: unless-stopped
    environment:
      - ENVIRONMENT=production
      - DEBUG=False
    env_file:
      - .env.production
    volumes:
      # Persist database file
      - ../../data:/app/data
      # Persist uploaded receipts and invoices
      - ../../receipts:/app/receipts
      - ../../rechnungen:/app/rechnungen
      # Persist logs
      - ../../logs:/app/logs
    networks:
      - erp-network

  # Nginx Reverse Proxy
  nginx:
    image: nginx:alpine
    container_name: buildflow-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ../nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ../nginx/conf.d:/etc/nginx/conf.d:ro
      - ../../certbot/conf:/etc/letsencrypt:ro
      - ../../certbot/www:/var/www/certbot:ro
    networks:
      - erp-network
    depends_on:
      - app
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"

  # Certbot for SSL certificates
  certbot:
    image: certbot/certbot
    container_name: buildflow-certbot
    restart: "no"
    volumes:
      - ../../certbot/conf:/etc/letsencrypt
      - ../../certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

networks:
  erp-network:
    driver: bridge

volumes:
  erp-data:
    driver: local